### ISSUE TITLE
mybinder.org link not working 

### ISSUE THREAD

**Issue by gregnewkirk** [jperkel/example_notebook#1]
Error log given: 
`ERROR: Command "/srv/conda/envs/notebook/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-w0i1k2n9/pandas/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-eteh1_pg/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-w0i1k2n9/pandas/
Removing intermediate container bbd3c863aef3
The command '/bin/sh -c ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r "requirements.txt"' returned a non-zero code: 1<class 'str'>`

**Comment by jperkel** [comment]
I'll take a look, and thanks for flagging. This more recent example does work: https://github.com/jperkel/Mapping-tools-examples.

**Comment by myfriendedward** [comment]
Error log:
`ERROR: Command errored out with exit status 1: /srv/conda/envs/notebook/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ckfxlq9i/pandas/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ckfxlq9i/pandas/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l2kcd7il/install-record.txt --single-version-externally-managed --compile --install-headers /srv/conda/envs/notebook/include/python3.7m/pandas Check the logs for full command output.`

**Comment by jperkel** [comment]
@myfriendedward : Thanks for flagging this. Fixed now -- I had to update `requirements.txt` with new version numbers. And I updated the notebook itself to accommodate changes in the NCBI Entrez database.
